# Generated by Django 6.0.2 on 2026-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Контактні дані')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
