# Generated by Django 6.0.2 on 2026-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickcontact',
            name='contact_info',
            field=models.CharField(max_length=255),
        ),
    ]
